### PR TITLE
Compatibility upgrade

### LINKED ISSUE #153: Django 4 support
Hello!
Django 4.0 is out but this project pins Django version to `<4.0` and prevents upgrade.

I tried to run `make test` locally to check if it will work "as is" but I keep getting errors during `pip install` phase - like these:  
`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '//django_rest_social_auth/venv/lib/python3.7/site-packages/typing_extensions.py'`
I don't know if these errors are caused by this strange `//` in the beginning of the path or by some environment mismatch (I tried on Arch Linux, Docker 20.10.12) and I failed to make it work.

Maybe you can check if it works with 4.0?  `social-core` and `social-app-django` work with Python 3.10 / Django 4.0 so I think there are chances that your package is already compatible too.

### PR DESCRIPTION
**Pull request by KOliver94**
- Add support for Django 4.0 (fixes #153)
- Add support for Python 3.10
- Drop support for Django 2.2, 3.0, 3.1
- Drop support for Python 3.6
- Fix import error introduced by me in #152 
- Update requirements

### CODE REVIEW

**Review by mrfroggg — APPROVED** [review]

**Comment by KOliver94** [comment]
Hi @st4lk,

Can you review my PRs? I would like to keep this package maintained because I find it really useful.

Thanks!

**Review by dkarchmer — APPROVED** [review]
Code looks good to me

**Comment by KOliver94** [comment]
Hi @st4lk,

I opened this PR a month ago. Can you take a look at it?

Thanks!

**Comment by tuergeist** [comment]
@KOliver94 @dkarchmer As it looks like this will never be merged back, did you already opened a fork?

**Comment by KOliver94** [comment]
I have a fork with a branch called [next](https://github.com/KOliver94/django-rest-social-auth/tree/next) which contains all my changes which are waiting here to be merged. I use it for my project.

**Comment by st4lk** [comment]
Hey guys,
really sorry for delay.

The changes are merged here (with minor changes):
https://github.com/st4lk/django-rest-social-auth/pull/166

Thanks for assistance!

**Comment by st4lk** [comment]
Available in pypi [rest-social-auth v8.0.0](https://pypi.org/project/rest-social-auth/8.0.0/)

**Pull request closed without merging**
