### PR TITLE
Document Oauth1 support and bump version.

### PR DESCRIPTION
**Pull request by skolsuper**
I have added some documentation for OAuth1 support.  It would also be nice if you could push a new version to PyPI with a higher version number, pip-tools doesn't play all that well with editable dependencies so it would make my life a little bit easier.

Finally, it would be very cool if you could add a place to list contributors.

### CODE REVIEW

**Comment by st4lk** [comment]
Hi, James!
Thanks for activity!
Currently i'm stuck on my work, but i'll return to this project on next week.

**Comment by st4lk** [comment]
James, thanks again, it is merged now!
I added contributors list to the end of readme, hope it will be ok.
Also made some changes, for example it is now possible to specify provider in url, not in request body.
Rewrite example project, it using [satellizer](https://github.com/sahat/satellizer) now.
I will upload new version to pypi in next couple of days i think.

**Comment by skolsuper** [comment]
Awesome, thanks very much for the credit Alexey.  I will contribute anything more I can add, as I keep using this package in every project.  Thanks again for sharing!

**Comment by st4lk** [comment]
Uploaded [v0.3.0](https://pypi.python.org/pypi/rest_social_auth/0.3.0) to pypi now.

**Pull request merged**
