### PR TITLE
Compatibility upgrade

### PR DESCRIPTION
**Pull request by KOliver94**
Hey @st4lk,

As Django 4.2 and Python 3.11 have been released I added them to the test matrix and as everything passed I added them as supported.

Can you take a look please?

Thanks!

### CODE REVIEW

**Comment by alextatarinov** [comment]
@st4lk, could you please merge this?

**Comment by mirzadelic** [comment]
@st4lk will this soon be merged?

**Comment by st4lk** [comment]
Hey guys, thanks for this. Will check today and merge

**Review by st4lk — APPROVED** [review]

**Comment by st4lk** [comment]
Published in [v8.1.0](https://pypi.org/project/rest-social-auth/8.1.0/) on pypi, thanks again!

**Pull request merged**
