### PR TITLE
Add compatibility for social-auth-app-django 5.x.x

### LINKED ISSUE #149: social-auth-app-django 5.0.0 support
social-auth-app-django 5.0.0 is already out, and it fixes a deprecation issue:

> Switch from deprecated django.conf.urls.url to django.urls.path

Therefore, it would be nice to add support for it

### PR DESCRIPTION
**Pull request by KOliver94**
Thanks for the great package!

I checked the newer version of social-auth-app-django and it does not seem to break anything here but fixes some deprecation issues with more recent Django versions. I ran the provided tox tests and they all passed. While doing that I fixed some test warnings, added Django 3.2 to the test environment matrix and fixed issue with Python 3.9 tests not running.

Closes #149

### CODE REVIEW

**Comment by sp-ivan-alcoceba** [comment]
Hi @st4lk,

it would be really useful if you can take a look at this PR and merge it if it is correct.

**Comment by mohi7solanki** [comment]
+1 for this PR @st4lk

**Comment by st4lk** [comment]
Thanks guys!
Will check and bump a new version to pypi soon.

**Review by st4lk — APPROVED** [review]

**Comment by st4lk** [comment]
[v7.0.0](https://pypi.org/project/rest-social-auth/7.0.0/) in pypi now

**Pull request merged**
