### PR TITLE
Separate into a method the parsing of request data...

### PR DESCRIPTION
**Pull request by skolsuper**
... for easier overriding by subclasses.

### CODE REVIEW

**Comment by st4lk** [comment]
Thanks, James!
I just added 'in' to method name to be more explicit, i.e. `get_serializer_in_data`

**Comment by skolsuper** [comment]
:+1:  Good point.  If you're interested, I've hacked together a working OAuth1 version for Twitter login for my site.

**Comment by skolsuper** [comment]
It's done in my project at the minute but I could try to factor it into rest_social_auth and make a PR if you have time to review it.

**Comment by st4lk** [comment]
Sure, sounds great!

**Pull request merged**
